### ISSUE TITLE
java.lang.IllegalArgumentException: Version mismatch error

### ISSUE THREAD

**Issue by rajcspsg** [51Degreesmobi/51Degrees-Java#10]
Hi,

when I try to run few examples under `device-detection-examples`, I always get below exception.

Exception in thread "main" java.lang.IllegalArgumentException: Version mismatch. Data is version 1936876918.544108393.1886680168.791624307for PatternV31: 3.1.0.0 PatternV32: 3.2.0.0 reader
	at fiftyone.mobile.detection.factories.CommonFactory.loadHeader(CommonFactory.java:64)
	at fiftyone.mobile.detection.factories.MemoryFactory.load(MemoryFactory.java:239)
	at fiftyone.mobile.detection.factories.MemoryFactory.create(MemoryFactory.java:216)
	at fiftyone.mobile.detection.factories.MemoryFactory.create(MemoryFactory.java:157)
	at fiftyone.mobile.detection.factories.MemoryFactory.create(MemoryFactory.java:140)
	at fiftyone.device.example.illustration.MetadataExample.<init>(MetadataExample.java:92)
	at fiftyone.device.example.illustration.MetadataExample.main(MetadataExample.java:153)

Do I need to change any settings while I run the program.

**Comment by JoshGrew51D** [comment]
Hi There

First thing would be to check if the versions of the data file you currently have in the [data](https://github.com/51Degrees/Java-Device-Detection/tree/master/data) folder are empty. By default they are included as empty templates when you clone the repository unless you have Git LFS installed.  

The Lite data files can be downloaded manually from the link above and all others are available on our website.

Let me know how you get on.

**Comment by rajcspsg** [comment]
Thanks @JoshGrew51D 
I see the data folder is missing data and contains only 2 lines with SHA values. I manually downloaded the files and run the device-detection-examples and they are executing fine.

When I run the command `mvn clean test` I get below error - 
```
Disposed of data set from file '../data/51Degrees-PremiumV3.2.dat'
Tests run: 13, Failures: 0, Errors: 0, Skipped: 13, Time elapsed: 0.022 sec - in fiftyone.mobile.test.type.performance.premium.V32PremiumPerformanceMemoryTest

Results :

Failed tests:
  DatasetBuilderTest.testGuavaCache:158 expected:<1.0> but was:<2.0>
  StreamFactoryTest.testDefaultCache:94 expected:<1.0> but was:<2.0>
Tests in error:
  AutoUpdateTest.testUpgradeLite:64->AutoUpdateBase.setLiteDataFile:64->AutoUpdateBase.copyFileUsingStream:73 » FileNotFound

Tests run: 521, Failures: 2, Errors: 1, Skipped: 328
```

Any Idea?

**Comment by JoshGrew51D** [comment]
As part of a recent fix we added in an additional test for cache requests. The error seems to be an oversight where it is still expecting 1 test as opposed to 2.

I have sent you an Email with a patch for you to apply that will resolve the issue. I will add this fix shortly.

**Comment by JoshGrew51D** [comment]
I am going to close this issue for now. The hotfix for cache requests has been applied and will resolve the issue.

Please let me know how you get on. Any further issues just get in touch and I will be happy to re-open.
